CREATE TABLE covid (
    state VARCHAR PRIMARY KEY,
    tested NUMERIC,
	infected NUMERIC,
	deaths NUMERIC,
	population NUMERIC,
	pop_density NUMERIC,
	gini NUMERIC,
	icu_beds NUMERIC,
	income NUMERIC,
	GDP NUMERIC,
	employment NUMERIC,
	sex_ratio NUMERIC,
	smoking NUMERIC,
	flu_deaths NUMERIC,
	REspiratory NUMERIC,
	Physician NUMERIC,
	Hospitals NUMERIC,
	health_spending NUMERIC,
	pollution NUMERIC,
	airport NUMERIC,
	temperature NUMERIC,
	urban NUMERIC,
	adolescent NUMERIC,
	adult NUMERIC,
	senior_citizen NUMERIC,
	school_date VARCHAR
	);
	
	SELECT * FROM covid;